{% set version = "2.1.9" %}

package:
  name: bob.ip.flandmark
  version: {{ version }}

source:
  fn: bob.ip.flandmark-{{ version }}.zip
  md5: a3769516de0af59ad91092872ddc9263
  url: https://pypi.io/packages/source/b/bob.ip.flandmark/bob.ip.flandmark-{{ version }}.zip

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.io.image
    - bob.ip.base
    - bob.ip.color
    - bob.ip.draw
    - matplotlib
    - boost 1.61.*
    - pkg-config

  run:
    - python
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.io.image
    - bob.ip.base
    - bob.ip.color
    - bob.ip.draw
    - matplotlib
    - boost 1.61.*

test:
  commands:
    - nosetests -sv bob.ip.flandmark

  imports:
    - bob
    - bob.ip
    - bob.ip.flandmark

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: GNU General Public License v3 (GPLv3)
  summary: Python bindings to the flandmark keypoint localization library

extra:
  recipe-maintainers:
    - 183amir
