# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "M/jWKPpZCeZfra0OalG8daBnCKLcUPp14tOA18ne6SCfQwPH8OGE+kRvh3JoWEQjmIqBSqOdJLCgY1L0404p1k5HTm0C4YvxPp5Yt+nQKU5/uWj+GO9PwgDsjrfKtQoADMFTxmBKcu4kFD6P1Af6QAzz7aRg32q/ab3Cb5L0LlWELiQs1AdNDrgIfVF3nEs6RCBFCI6UkVU7dgC+I0PQW4hjDp3CrElLAYEGyn8ucGm/mUDWUD0btQUGawuQ+gRRQT0N51VFCOMUxAj3JKDaGTVlo+498GKxpq22rVtKHa6OcGD8CmNZ8NGr07DEEubQyNta6ITSgKhTn/pIFOjBfeDC5Wj7+b2ub9w5EbYOvsHlvfjf5FdeWhzMoOwyd8jUmuKjltQKvt/c9VV+J7J9ZdYtzUsTCkriXRDzkujZk75RHlzypYjtz5Xdq3NfIWeXUZI/nrC6L2SwyESz78+Zxaw8v+KJd6kUHW/EpPJrJbiwabRfy7F/ul16++XqDFXA+OjfExKv/0hHk6p+jqdSuD4D0L6xAh4wKpaLD1w8EHee9ElIIlqN+ouWUIybjYCpw9hRA6xlU75ksWtLgAAbsvgFrckyrgeS+4451UuRLcwca3vu/z5pP56TwW+4fERe8NpoYAAI55zMjionsilfDgVomML3cw44NADITWGfjfM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
